In [8]:
# --- IMPORTS ---
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

# --- NEW XGBOOST IMPORT ---
from xgboost import XGBRegressor

print("Starting Machine Learning Pipeline...")

Starting Machine Learning Pipeline...

## Models without Grid

In [2]:
print("Loading databases into memory...")

RESULTS_DIR= "data/processed"
# Read each CSV file into its own DataFrame
df1 = pd.read_csv(f"{RESULTS_DIR}/df1_baseline.csv")
df2 = pd.read_csv(f"{RESULTS_DIR}/df2_decisiontree.csv")
df3 = pd.read_csv(f"{RESULTS_DIR}/df3_regressiondata_removedoutliers.csv")
df4 = pd.read_csv(f"{RESULTS_DIR}/df4_weather_condition.csv")
df5 = pd.read_csv(f"{RESULTS_DIR}/df5_baseline_ro.csv")

print("All 4 databases loaded successfully!")

# Quick verification check
print(f"Database 1 Shape: {df1.shape}")
print(f"Database 2 Shape: {df2.shape}")
print(f"Database 3 Shape: {df3.shape}")
print(f"Database 4 Shape: {df4.shape}")
print(f"Database 5 Shape: {df5.shape}")

Loading databases into memory...
All 4 databases loaded successfully!
Database 1 Shape: (8465, 14)
Database 2 Shape: (8465, 13)
Database 3 Shape: (8313, 13)
Database 4 Shape: (8465, 13)
Database 5 Shape: (8465, 14)

In [62]:
features_1 = df1.drop(columns=["Rented_Bike_Count"])
target_1 = df1["Rented_Bike_Count"]

X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(features_1, target_1, test_size = 0.20, random_state=0)

In [63]:
num_cols = X_train_1.select_dtypes(include='number').columns

scaler = StandardScaler()

X_train_norm_1 = X_train_1.copy()
X_test_norm_1 = X_test_1.copy()

X_train_norm_1[num_cols] = scaler.fit_transform(X_train_1[num_cols])

X_test_norm_1[num_cols] = scaler.transform(X_test_1[num_cols])

In [64]:
features_2 = df2.drop(columns=["Rented_Bike_Count"])
target_2 = df2["Rented_Bike_Count"]

X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(features_2, target_2, test_size = 0.20, random_state=0)

In [65]:
num_cols = X_train_2.select_dtypes(include='number').columns

scaler = StandardScaler()

X_train_norm_2 = X_train_2.copy()
X_test_norm_2 = X_test_2.copy()

X_train_norm_2[num_cols] = scaler.fit_transform(X_train_2[num_cols])

X_test_norm_2[num_cols] = scaler.transform(X_test_2[num_cols])

In [3]:
features_3 = df3.drop(columns=["Rented_Bike_Count"])
target_3 = df3["Rented_Bike_Count"]

X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(features_3, target_3, test_size = 0.20, random_state=0)

In [67]:
num_cols = X_train_3.select_dtypes(include='number').columns

scaler = StandardScaler()

X_train_norm_3 = X_train_3.copy()
X_test_norm_3 = X_test_3.copy()

X_train_norm_3[num_cols] = scaler.fit_transform(X_train_3[num_cols])

X_test_norm_3[num_cols] = scaler.transform(X_test_3[num_cols])

In [68]:
features_4 = df4.drop(columns=["Rented_Bike_Count"])
target_4 = df4["Rented_Bike_Count"]

X_train_4, X_test_4, y_train_4, y_test_4 = train_test_split(features_4, target_4, test_size = 0.20, random_state=0)

In [69]:
num_cols = X_train_4.select_dtypes(include='number').columns

scaler = StandardScaler()

X_train_norm_4 = X_train_4.copy()
X_test_norm_4 = X_test_4.copy()

X_train_norm_4[num_cols] = scaler.fit_transform(X_train_4[num_cols])

X_test_norm_4[num_cols] = scaler.transform(X_test_4[num_cols])

In [4]:
features_5 = df5.drop(columns=["Rented_Bike_Count"])
target_5 = df5["Rented_Bike_Count"]

X_train_5, X_test_5, y_train_5, y_test_5 = train_test_split(features_5, target_5, test_size = 0.20, random_state=0)

In [71]:
num_cols = X_train_5.select_dtypes(include='number').columns

scaler = StandardScaler()

X_train_norm_5 = X_train_5.copy()
X_test_norm_5 = X_test_5.copy()

X_train_norm_5[num_cols] = scaler.fit_transform(X_train_5[num_cols])

X_test_norm_5[num_cols] = scaler.transform(X_test_5[num_cols])

In [72]:
datasets = [

    # DATASET 1 (df1_baseline)
    {
        "name": "df1_baseline",
        "X_train": X_train_1,
        "X_test": X_test_1,
        "y_train": y_train_1,
        "y_test": y_test_1
    },

    # DATASET 1 (df1_baseline_normalized)
    {
        "name": "df1_normalized",
        "X_train": X_train_norm_1,
        "X_test": X_test_norm_1,
        "y_train": y_train_1,
        "y_test": y_test_1
    },

    # DATASET 2 (df2_decision_tree)
    {
        "name": "df2_decision_tree",
        "X_train": X_train_2,
        "X_test": X_test_2,
        "y_train": y_train_2,
        "y_test": y_test_2
    },
    # DATASET 2 (df2_decision_tree_normalized)
    {
        "name": "df2_normalized",
        "X_train": X_train_norm_2,
        "X_test": X_test_norm_2,
        "y_train": y_train_2,
        "y_test": y_test_2
    },

    # DATASET 3 (raw)
     {
        "name": "df3_removedoutliers",
        "X_train": X_train_3,
        "X_test": X_test_3,
        "y_train": y_train_3,
        "y_test": y_test_3
    },

    # DATASET 3 (df3_normalized)
    {
        "name": "df3_normalized",
        "X_train": X_train_norm_3,
        "X_test": X_test_norm_3,
        "y_train": y_train_3,
        "y_test": y_test_3
    },

    # DATASET 4 (df4_weather_condition)
    {
        "name": "df4_weather_condition",
        "X_train": X_train_4,
        "X_test": X_test_4,
        "y_train": y_train_4,
        "y_test": y_test_4
    },

    # DATASET 4 (df4_weather_condition_normalized)
    {
        "name": "df4_normalized",
        "X_train": X_train_norm_4,
        "X_test": X_test_norm_4,
        "y_train": y_train_4,
        "y_test": y_test_4
    }, 
    # DATASET 5 (df5_baseline_ro)
    {
        "name": "df5_baseline_ro",
        "X_train": X_train_5,
        "X_test": X_test_5,
        "y_train": y_train_5,
        "y_test": y_test_5
    },

    # DATASET 5 (df5_baseline_ro)
    {
        "name": "df5_baseline_ro",
        "X_train": X_train_norm_5,
        "X_test": X_test_norm_5,
        "y_train": y_train_5,
        "y_test": y_test_5
    }
]

In [73]:
print(f"DB 1 Training shapes: X={X_train_1.shape}, y={y_train_1.shape}")
print(f"DB 2 Training shapes: X={X_train_2.shape}, y={y_train_2.shape}")
print(f"DB 3 Training shapes: X={X_train_3.shape}, y={y_train_3.shape}")
print(f"DB 4 Training shapes: X={X_train_4.shape}, y={y_train_4.shape}")
print(f"DB 5 Training shapes: X={X_train_5.shape}, y={y_train_5.shape}")

DB 1 Training shapes: X=(6772, 13), y=(6772,)
DB 2 Training shapes: X=(6772, 12), y=(6772,)
DB 3 Training shapes: X=(6650, 12), y=(6650,)
DB 4 Training shapes: X=(6772, 12), y=(6772,)
DB 5 Training shapes: X=(6772, 13), y=(6772,)

In [74]:
models = [
    {"name": "LinearRegression", "model": LinearRegression()},
    
    {"name": "RandomForest",
     "model": RandomForestRegressor(
         n_estimators=100,
         max_depth=20,
         random_state=42
     )},
    
    {"name": "XGBoost",
     "model": XGBRegressor(
         n_estimators=100,
         max_depth=6,
         learning_rate=0.1,
         random_state=42
     )}
]

In [75]:
results = []

for ds in datasets:
    for m in models:

        m["model"].fit(ds["X_train"], ds["y_train"])

        pred = m["model"].predict(ds["X_test"])

        results.append({
            "dataset": ds["name"],
            "model": m["name"],
            "MAE": mean_absolute_error(ds["y_test"], pred),
            "RMSE": np.sqrt(mean_squared_error(ds["y_test"], pred)),
            "R2": r2_score(ds["y_test"], pred),
        })

        print(f"{ds['name']:>12} | {m['name']:<16} done")

results_df = (
    pd.DataFrame(results)
      .sort_values("R2", ascending=False)
      .reset_index(drop=True)
)

results_df

df1_baseline | LinearRegression done
df1_baseline | RandomForest     done
df1_baseline | XGBoost          done
df1_normalized | LinearRegression done
df1_normalized | RandomForest     done
df1_normalized | XGBoost          done
df2_decision_tree | LinearRegression done
df2_decision_tree | RandomForest     done
df2_decision_tree | XGBoost          done
df2_normalized | LinearRegression done
df2_normalized | RandomForest     done
df2_normalized | XGBoost          done
df3_removedoutliers | LinearRegression done
df3_removedoutliers | RandomForest     done
df3_removedoutliers | XGBoost          done
df3_normalized | LinearRegression done
df3_normalized | RandomForest     done
df3_normalized | XGBoost          done
df4_weather_condition | LinearRegression done
df4_weather_condition | RandomForest     done
df4_weather_condition | XGBoost          done
df4_normalized | LinearRegression done
df4_normalized | RandomForest     done
df4_normalized | XGBoost          done
df5_baseline_ro | LinearRegression done
df5_baseline_ro | RandomForest     done
df5_baseline_ro | XGBoost          done
df5_baseline_ro | LinearRegression done
df5_baseline_ro | RandomForest     done
df5_baseline_ro | XGBoost          done

                  dataset             model         MAE        RMSE        R2
0          df3_normalized           XGBoost   98.735847  158.698958  0.926798
1     df3_removedoutliers           XGBoost   98.735847  158.698958  0.926798
2          df3_normalized      RandomForest   97.530253  164.093924  0.921736
3     df3_removedoutliers      RandomForest   97.574561  164.185984  0.921648
4            df1_baseline           XGBoost  103.540962  177.363531  0.919959
5          df1_normalized           XGBoost  103.540962  177.363531  0.919959
6         df5_baseline_ro           XGBoost  103.540962  177.363531  0.919959
7         df5_baseline_ro           XGBoost  103.540962  177.363531  0.919959
8         df5_baseline_ro      RandomForest  107.119319  188.007773  0.910063
9          df1_normalized      RandomForest  107.119319  188.007773  0.910063
10           df1_baseline      RandomForest  107.357027  188.108377  0.909967
11        df5_baseline_ro      RandomForest  107.357027  188.108377  0.909967
12         df2_normalized           XGBoost  108.049393  191.399370  0.906789
13      df2_decision_tree           XGBoost  108.049393  191.399370  0.906789
14      df2_decision_tree      RandomForest  112.964312  204.936558  0.893138
15         df2_normalized      RandomForest  112.947658  205.128089  0.892938
16         df4_normalized           XGBoost  129.089859  217.086451  0.880091
17  df4_weather_condition           XGBoost  128.525024  217.338455  0.879813
18         df4_normalized      RandomForest  137.165433  239.555417  0.853985
19  df4_weather_condition      RandomForest  137.283265  240.124374  0.853291
20         df3_normalized  LinearRegression  297.202130  387.164894  0.564319
21    df3_removedoutliers  LinearRegression  297.202130  387.164894  0.564319
22        df5_baseline_ro  LinearRegression  321.572239  429.590404  0.530437
23           df1_baseline  LinearRegression  321.572239  429.590404  0.530437
24         df1_normalized  LinearRegression  321.572239  429.590404  0.530437
25        df5_baseline_ro  LinearRegression  321.572239  429.590404  0.530437
26      df2_decision_tree  LinearRegression  326.989862  434.618356  0.519381
27         df2_normalized  LinearRegression  326.989862  434.618356  0.519381
28         df4_normalized  LinearRegression  329.878144  439.344025  0.508873
29  df4_weather_condition  LinearRegression  329.878144  439.344025  0.508873

In [76]:
average_bikes = df1['Rented_Bike_Count'].mean()
print(f"Average bikes rented per hour: {average_bikes:.0f}")

# Let's say your XGBoost MAE was 150
error_percentage = (150 / average_bikes) * 100
print(f"Your error is only about {error_percentage:.1f}% of the average volume!")

Average bikes rented per hour: 729
Your error is only about 20.6% of the average volume!

In [77]:
# 1. Train a quick Decision Tree on Database 1
detective_tree = DecisionTreeRegressor(random_state=42)
detective_tree.fit(datasets[0]["X_train"], datasets[0]["y_train"])

# 2. Force it to confess which features it used!
importances = pd.Series(detective_tree.feature_importances_, index=datasets[0]["X_train"].columns)

print("🚨 FEATURE IMPORTANCE REPORT 🚨")
print("If any column is near 1.0, that is your leaked target!")
print("-" * 40)
print(importances.sort_values(ascending=False).head())

🚨 FEATURE IMPORTANCE REPORT 🚨
If any column is near 1.0, that is your leaked target!
----------------------------------------
Temperature        0.348458
Hour               0.321513
Solar_Radiation    0.100725
Humidity           0.099584
DayOfWeek          0.039902
dtype: float64

# Models with Grid

In [78]:
lr_model = LinearRegression()

lr_grid = {
    "fit_intercept": [True, False]
}

In [79]:
rf_model = RandomForestRegressor(random_state=42)

rf_grid = {
    "n_estimators": [100, 200],
    "max_depth": [10, 20, None],
    "max_features": ["sqrt", "log2"],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

In [80]:
xgb_model = XGBRegressor(random_state=42)

xgb_grid = {
    "n_estimators": [100, 200],
    "max_depth": [3, 6, 10],
    "learning_rate": [0.01, 0.1],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}

In [81]:
models = {
    "LinearRegression": (lr_model, lr_grid),
    "RandomForest": (rf_model, rf_grid),
    "XGBoost": (xgb_model, xgb_grid)
}

In [82]:
datasets = [

    # DATASET 1 (df1_baseline)
    {
        "name": "df1_baseline",
        "X_train": X_train_1,
        "X_test": X_test_1,
        "y_train": y_train_1,
        "y_test": y_test_1
    },

    # DATASET 1 (df1_baseline_normalized)
    {
        "name": "df1_normalized",
        "X_train": X_train_norm_1,
        "X_test": X_test_norm_1,
        "y_train": y_train_1,
        "y_test": y_test_1
    },

    # DATASET 2 (df2_decision_tree)
    {
        "name": "df2_decision_tree",
        "X_train": X_train_2,
        "X_test": X_test_2,
        "y_train": y_train_2,
        "y_test": y_test_2
    },
    # DATASET 2 (df2_decision_tree_normalized)
    {
        "name": "df2_normalized",
        "X_train": X_train_norm_2,
        "X_test": X_test_norm_2,
        "y_train": y_train_2,
        "y_test": y_test_2
    },

    # DATASET 3 (raw)
     {
        "name": "df3_removedoutliers",
        "X_train": X_train_3,
        "X_test": X_test_3,
        "y_train": y_train_3,
        "y_test": y_test_3
    },

    # DATASET 3 (df3_normalized)
    {
        "name": "df3_normalized",
        "X_train": X_train_norm_3,
        "X_test": X_test_norm_3,
        "y_train": y_train_3,
        "y_test": y_test_3
    },

    # DATASET 4 (df4_weather_condition)
    {
        "name": "df4_weather_condition",
        "X_train": X_train_4,
        "X_test": X_test_4,
        "y_train": y_train_4,
        "y_test": y_test_4
    },

    # DATASET 4 (df4_weather_condition_normalized)
    {
        "name": "df4_normalized",
        "X_train": X_train_norm_4,
        "X_test": X_test_norm_4,
        "y_train": y_train_4,
        "y_test": y_test_4
    }, 
    # DATASET 5 (df5_baseline_ro)
    {
        "name": "df5_baseline_ro",
        "X_train": X_train_5,
        "X_test": X_test_5,
        "y_train": y_train_5,
        "y_test": y_test_5
    },

    # DATASET 5 (df5_baseline_ro)
    {
        "name": "df5_baseline_ro",
        "X_train": X_train_norm_5,
        "X_test": X_test_norm_5,
        "y_train": y_train_5,
        "y_test": y_test_5
    } 
]

In [83]:
results = []

for ds in datasets:
    
    X_train = ds["X_train"]
    X_test = ds["X_test"]
    y_train = ds["y_train"]
    y_test = ds["y_test"]
    dataset_name = ds["name"]

    for model_name, (model, grid) in models.items():

        print(f"Running {model_name} on {dataset_name}")

        grid_search = GridSearchCV(
            estimator=model,
            param_grid=grid,
            cv=5,
            scoring="r2",   # or "neg_mean_squared_error"
            n_jobs=-1
        )

        grid_search.fit(X_train, y_train)

        best_model = grid_search.best_estimator_
        pred = best_model.predict(X_test)

        results.append({
            "dataset": dataset_name,
            "model": model_name,
            "best_cv_score": grid_search.best_score_,
            "MAE": mean_absolute_error(y_test, pred),
            "RMSE": np.sqrt(mean_squared_error(y_test, pred)),
            "R2": r2_score(y_test, pred),
            "best_params": grid_search.best_params_
        })

        print(f"{dataset_name} | {model_name} done")

Running LinearRegression on df1_baseline
df1_baseline | LinearRegression done
Running RandomForest on df1_baseline
df1_baseline | RandomForest done
Running XGBoost on df1_baseline
df1_baseline | XGBoost done
Running LinearRegression on df1_normalized
df1_normalized | LinearRegression done
Running RandomForest on df1_normalized
df1_normalized | RandomForest done
Running XGBoost on df1_normalized
df1_normalized | XGBoost done
Running LinearRegression on df2_decision_tree
df2_decision_tree | LinearRegression done
Running RandomForest on df2_decision_tree
df2_decision_tree | RandomForest done
Running XGBoost on df2_decision_tree
df2_decision_tree | XGBoost done
Running LinearRegression on df2_normalized
df2_normalized | LinearRegression done
Running RandomForest on df2_normalized
df2_normalized | RandomForest done
Running XGBoost on df2_normalized
df2_normalized | XGBoost done
Running LinearRegression on df3_removedoutliers
df3_removedoutliers | LinearRegression done
Running RandomForest on df3_removedoutliers
df3_removedoutliers | RandomForest done
Running XGBoost on df3_removedoutliers
df3_removedoutliers | XGBoost done
Running LinearRegression on df3_normalized
df3_normalized | LinearRegression done
Running RandomForest on df3_normalized
df3_normalized | RandomForest done
Running XGBoost on df3_normalized
df3_normalized | XGBoost done
Running LinearRegression on df4_weather_condition
df4_weather_condition | LinearRegression done
Running RandomForest on df4_weather_condition
df4_weather_condition | RandomForest done
Running XGBoost on df4_weather_condition
df4_weather_condition | XGBoost done
Running LinearRegression on df4_normalized
df4_normalized | LinearRegression done
Running RandomForest on df4_normalized
df4_normalized | RandomForest done
Running XGBoost on df4_normalized
df4_normalized | XGBoost done
Running LinearRegression on df5_baseline_ro
df5_baseline_ro | LinearRegression done
Running RandomForest on df5_baseline_ro
df5_baseline_ro | RandomForest done
Running XGBoost on df5_baseline_ro
df5_baseline_ro | XGBoost done
Running LinearRegression on df5_baseline_ro
df5_baseline_ro | LinearRegression done
Running RandomForest on df5_baseline_ro
df5_baseline_ro | RandomForest done
Running XGBoost on df5_baseline_ro
df5_baseline_ro | XGBoost done

In [84]:
results_df = (
    pd.DataFrame(results)
      .sort_values("R2", ascending=False)
      .reset_index(drop=True)
)

results_df

,dataset,model,best_cv_score,MAE,RMSE,R2,best_params
0,df3_normalized,XGBoost,0.915638,88.120865,151.645486,0.933160,"{'colsample_bytree': 1.0, 'learning_rate': 0.1..."
1,df3_removedoutliers,XGBoost,0.915638,88.120865,151.645486,0.933160,"{'colsample_bytree': 1.0, 'learning_rate': 0.1..."
2,df5_baseline_ro,XGBoost,0.940068,93.392792,168.444759,0.927806,"{'colsample_bytree': 1.0, 'learning_rate': 0.1..."
3,df5_baseline_ro,XGBoost,0.940068,93.392792,168.444759,0.927806,"{'colsample_bytree': 1.0, 'learning_rate': 0.1..."
4,df1_normalized,XGBoost,0.940068,93.392792,168.444759,0.927806,"{'colsample_bytree': 1.0, 'learning_rate': 0.1..."
5,df1_baseline,XGBoost,0.940068,93.392792,168.444759,0.927806,"{'colsample_bytree': 1.0, 'learning_rate': 0.1..."
6,df2_normalized,XGBoost,0.932143,100.030457,188.746896,0.909355,"{'colsample_bytree': 1.0, 'learning_rate': 0.1..."
7,df2_decision_tree,XGBoost,0.932143,100.030457,188.746896,0.909355,"{'colsample_bytree': 1.0, 'learning_rate': 0.1..."
8,df3_normalized,RandomForest,0.872661,119.391094,184.582332,0.900972,"{'max_depth': None, 'max_features': 'sqrt', 'm..."
9,df3_removedoutliers,RandomForest,0.872613,119.653223,184.817326,0.900720,"{'max_depth': None, 'max_features': 'sqrt', 'm..."
10,df5_baseline_ro,RandomForest,0.901248,130.471668,203.137118,0.895006,"{'max_depth': 20, 'max_features': 'sqrt', 'min..."
11,df1_normalized,RandomForest,0.901248,130.471668,203.137118,0.895006,"{'max_depth': 20, 'max_features': 'sqrt', 'min..."
12,df1_baseline,RandomForest,0.901084,130.960465,203.618928,0.894508,"{'max_depth': 20, 'max_features': 'sqrt', 'min..."
13,df5_baseline_ro,RandomForest,0.901084,130.960465,203.618928,0.894508,"{'max_depth': 20, 'max_features': 'sqrt', 'min..."
14,df4_normalized,XGBoost,0.882362,127.803581,214.327418,0.883120,"{'colsample_bytree': 1.0, 'learning_rate': 0.1..."
15,df4_weather_condition,XGBoost,0.882339,127.087288,214.592373,0.882831,"{'colsample_bytree': 1.0, 'learning_rate': 0.1..."
16,df2_decision_tree,RandomForest,0.894234,134.842329,218.511358,0.878512,"{'max_depth': 20, 'max_features': 'sqrt', 'min..."
17,df2_normalized,RandomForest,0.894169,134.897035,218.671840,0.878334,"{'max_depth': 20, 'max_features': 'sqrt', 'min..."
18,df4_normalized,RandomForest,0.861862,142.158406,227.350009,0.868485,"{'max_depth': 20, 'max_features': 'sqrt', 'min..."
19,df4_weather_condition,RandomForest,0.861796,141.779702,227.534634,0.868271,"{'max_depth': 20, 'max_features': 'sqrt', 'min..."
20,df3_normalized,LinearRegression,0.528804,297.202130,387.164894,0.564319,{'fit_intercept': True}
21,df3_removedoutliers,LinearRegression,0.528804,297.202130,387.164894,0.564319,{'fit_intercept': True}
22,df5_baseline_ro,LinearRegression,0.543373,321.572239,429.590404,0.530437,{'fit_intercept': True}
23,df1_baseline,LinearRegression,0.543373,321.572239,429.590404,0.530437,{'fit_intercept': True}
24,df1_normalized,LinearRegression,0.543373,321.572239,429.590404,0.530437,{'fit_intercept': True}
25,df5_baseline_ro,LinearRegression,0.543373,321.572239,429.590404,0.530437,{'fit_intercept': True}
26,df2_decision_tree,LinearRegression,0.533613,326.989862,434.618356,0.519381,{'fit_intercept': True}
27,df2_normalized,LinearRegression,0.533613,326.989862,434.618356,0.519381,{'fit_intercept': True}
28,df4_normalized,LinearRegression,0.513345,329.878144,439.344025,0.508873,{'fit_intercept': True}
29,df4_weather_condition,LinearRegression,0.513345,329.878144,439.344025,0.508873,{'fit_intercept': True}

These three models were run with Grid. We choose to add the normalize datasets because it was need it for Linear Regression.

### Model XGBOOST with Grid

In [5]:
xgb_model = XGBRegressor(random_state=42)
xgb_grid = {
    "n_estimators": [200, 500, 1000],

    "learning_rate": [0.01, 0.03, 0.05, 0.1],

    "max_depth": [3, 5, 7, 10],

    "min_child_weight": [1, 3, 5],

    "subsample": [0.6, 0.8, 1.0],

    "colsample_bytree": [0.6, 0.8, 1.0],

    "gamma": [0, 0.1, 0.3, 1],

    "reg_alpha": [0, 0.01, 0.1, 1],

    "reg_lambda": [1, 3, 5]
}

In [6]:
models = {"XGBoost": (xgb_model, xgb_grid)}

In [15]:
datasets = [
    # DATASET 3 (raw)
     {
        "name": "df3_removedoutliers",
        "X_train": X_train_3,
        "X_test": X_test_3,
        "y_train": y_train_3,
        "y_test": y_test_3
    }]

In [16]:
results = []

for ds in datasets:

    X_train = ds["X_train"]
    X_test = ds["X_test"]
    y_train = ds["y_train"]
    y_test = ds["y_test"]
    dataset_name = ds["name"]

    for model_name, (model, grid) in models.items():

        print(f"\nRunning {model_name} on {dataset_name}")

        search = RandomizedSearchCV(
            estimator=model,
            param_distributions=grid,
            n_iter=50,              # adjust depending on compute
            cv=5,
            scoring="r2",
            n_jobs=-1,
            verbose=1,
            random_state=42
        )

        search.fit(
            X_train,
            y_train
        )

        best_model = search.best_estimator_

        pred_train = best_model.predict(X_train)
        pred_test = best_model.predict(X_test)

        results.append({
            "dataset": dataset_name,
            "model": model_name,

            "best_cv_score": search.best_score_,

            "train_r2": r2_score(y_train, pred_train),
            "test_r2": r2_score(y_test, pred_test),

            "MAE": mean_absolute_error(y_test, pred_test),

            "RMSE": np.sqrt(
                mean_squared_error(y_test, pred_test)
            ),

            "R2": r2_score(y_test, pred_test),

            "best_params": search.best_params_
        })

        print(f"{dataset_name} | {model_name} done")


results_df = pd.DataFrame(results)

results_df.sort_values(
    by="R2",
    ascending=False
)

Running XGBoost on df3_removedoutliers
Fitting 5 folds for each of 50 candidates, totalling 250 fits
df3_removedoutliers | XGBoost done

,dataset,model,best_cv_score,train_r2,test_r2,MAE,RMSE,R2,best_params
0,df3_removedoutliers,XGBoost,0.918687,0.999999,0.936081,86.942406,148.294662,0.936081,"{'subsample': 0.6, 'reg_lambda': 5, 'reg_alpha..."

df.loc[4333]
Date                         30/05/2018
Rented Bike Count                  1134
Hour                                 13
Temperature(°C)                    24.0
Humidity(%)                          56
Wind speed (m/s)                    2.6
Visibility (10m)                   1282
Dew point temperature(°C)          14.6
Solar Radiation (MJ/m2)            2.94
Rainfall(mm)                        0.0
Snowfall (cm)                       0.0
Seasons                          Spring
Holiday                      No Holiday
Functioning Day                     Yes

In [ ]:
# 1. Create a "mock" forecast for tomorrow!
# CRITICAL: The names here MUST exactly match the columns in your X_train!
# If you used dummy variables (like DayOfWeek_Monday), you must include them too.
new_scenario = {
    'Hour': [13],                 # 5:00 PM (Rush hour)
    'Temperature': [24.0],        # A beautiful 22.5°C day
    'Humidity': [56],             # Comfortable humidity
    'Wind_Speed': [2.6],          # Light breeze
    'Visibility': [1282],         # Clear skies
    'Solar_Radiation': [2.94],
    'Holiday': [0],
    'DayOfWeek_sin': [-0.433884], 
    'DayOfWeek_cos': [-0.900969],
    'Spring': [1],# Sunny
    'Summer': [0],            
    'Autumn': [0]       
    # Add any other columns your specific dataset has! 
    
}

In [30]:
future_data = pd.DataFrame(new_scenario)

# Ensure same feature order
future_data = future_data[X_train.columns]

# Predict
predicted_bikes = best_model.predict(future_data)

print("🚴‍♂️ --- AI PREDICTION --- 🚴‍♂️")
print("Under these exact conditions, the model expects:")
print(f"{predicted_bikes[0]:.0f} bicycles to be rented!")

🚴‍♂️ --- AI PREDICTION --- 🚴‍♂️
Under these exact conditions, the model expects:
1317 bicycles to be rented!